AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'db/seeds.rb'

Style/LambdaCall:
  EnforcedStyle: 'braces'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'spec/spec_helper.rb'

Documentation:
  Enabled: false
